//===-- offload-arch/OffloadArch.cpp ----------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
///
/// \file  amdgpu/vendor_specific_capabilities.cpp
///
/// Implementiton of _aot_amdgpu_capabilities() function for offload-arch tool.
/// This is only called with the -r flag to show all runtime capabilities that
/// would satisfy requirements of the compiled image.
///
//===----------------------------------------------------------------------===//

#include "llvm/OffloadArch/OffloadArch.h"

std::string _aot_intelhd_capabilities(uint16_t vid, uint16_t devid,
                                      std::string oa) {
  std::string intelhd_capabilities;
  /* add code here to detect intelhd capabilities for any intelhd requirements
   * that may be generated by clang compiler
   */
  return intelhd_capabilities;
}
